version: '3'
services: 
    web:
        # if we are using Dockerfile then we can just simply as below otherwise we need to provide few parameters which is show after that
        #build: .
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
